services:
  gauth:
    image: postgres:latest
    container_name: gauth
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: gauth
    ports:
      - "7323:5432"
    volumes:
      - gauth-data:/var/lib/postgresql/data
      - ./postgres.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d gauth -h 127.0.0.1 -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2" 

volumes:
  gauth-data:

# postgresql://admin:admin123@localhost:7323/gauth
